"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
required: ["bridge", "auth"]
properties:
    bridge:
        type: "object"
        required: ["domain", "homeserverUrl"]
        properties:
          domain:
            type: "string"
          homeserverUrl:
            type: "string"
          presenceInterval:
            type: "number"
          disablePresence:
            type: "boolean"
          disableTypingNotifications:
            type: "boolean"
          disableDiscordMentions:
            type: "boolean"
          disableDeletionForwarding:
            type: "boolean"
          enableSelfServiceBridging:
            type: "boolean"
    auth:
        type: "object"
        required: ["botToken"]
        properties:
          clientID:
            type: "string"
          secret:
            type: "string"
          botToken:
            type: "string"
    logging:
        type: "object"
        required: []
        properties:
          console:
            type: "string"
            enum: ["error", "warn", "info", "verbose", "silly", "silent"]
          lineDateFormat:
            type: "string"
          files:
            type: "array"
            items:
              type: "object"
              required: ["file"]
              properties:
                file:
                  type: "string"
                level:
                  type: "string"
                  enum: ["error", "warn", "info", "verbose", "silly"]
                maxFiles:
                  type: "string"
                maxSize:
                  type: ["number", "string"]
                datePattern:
                  type: "string"
                enabled:
                  type: "array"
                  items:
                    type: "string"
                disabled:
                  type: "array"
                  items:
                    type: "string"
    database:
        type: "object"
        required: ["filename"]
        properties:
          filename:
            type: "string"
          userStorePath:
            type: "string"
          roomStorePath:
            type: "string"
    room:
        type: "object"
        required: ["defaultVisibility"]
        properties:
          defaultVisibility:
            type: "string"
